CarrierWave.configure do |config|

config.fog_public = false 
#config.fog_authenticated_url_expiration = 120 #300=5min, time (in seconds) that authenticated urls
    #   will be valid, when fog_public is false and provider is AWS or Google, defaults to 600

  if Rails.env.development? || Rails.env.test?
    config.storage = :file
  else
    # config.cache_dir = "#{Rails.root}/tmp/uploads"
    
    config.fog_credentials = {
      :provider                         => 'Google',
      :google_storage_access_key_id     => ENV['GOOGLE_ID_KEY'],
      :google_storage_secret_access_key => ENV['GOOGLE_ACCESS_KEY']
    }
    config.fog_directory = ENV['GOOGLE_DIRECTORY']

    # generated by running SecureRandom.uuid in console
    # see docs https://cloud.google.com/storage/docs/best-practices
    # https://cloud.google.com/storage/docs/bucket-naming?hl=en#requirements
  end
  
end
